import { Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata = {
  title: "AJ Lash Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <Header />
          {children}
      </body>
    </html>
  );
}

export { playfair };